"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Import scss
import "./../assets/scss/theme.scss";
import "./../assets/scss/preloader.scss";

// layouts Format
import VerticalLayout from "@/components/VerticalLayout/";
// import NonAuthLayout from "@/components/NonAuthLayout";
import { createSelector } from "reselect";
import { Provider } from "react-redux";
import { configureStore } from "./store/index";
const inter = Inter({ subsets: ["latin"] });

//redux
import { useSelector } from "react-redux";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

function RootLayout({ children }: { children: React.ReactNode }) {
  const selectCalendar = createSelector(
    (state: any) => state.Layout,
    (state) => ({
      layoutType: state.layoutType,
    })
  );

  // const { layoutType } = useSelector(selectCalendar);

  function getLayout() {
    let layoutCls: Object = VerticalLayout;
    // switch (layoutType) {
    //   case "horizontal":
    //  let layoutCls = HorizontalLayout;
    //     break;
    //   default:
    layoutCls = VerticalLayout;
    //     break;
    // }
    return layoutCls;
  }

  const Layout: any = getLayout();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={configureStore({})}>
          <Layout>{children}</Layout>
        </Provider>
      </body>
    </html>
  );
}

export default RootLayout;
